version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: iot
      POSTGRES_PASSWORD: iot
      POSTGRES_DB: iot_smartlock
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  mosquitto:
    image: eclipse-mosquitto:2
    ports: ["1883:1883", "9001:9001"]
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  backend:
    build: ./backend
    env_file: ./backend/.env
    ports: ["4000:4000"]
    depends_on: [postgres, mosquitto]
    volumes: ["./backend:/app", "/app/node_modules"]

  web-admin:
    build: ./web-admin
    ports: ["5173:5173"]
    depends_on: [backend]
    volumes: ["./web-admin:/app", "/app/node_modules"]

  device-simulator:
    build: ./device-simulator
    depends_on: [mosquitto]
    volumes: ["./device-simulator:/app", "/app/node_modules"]

volumes:
  pgdata: